### ISSUE TITLE
Retour correcteur

### ISSUE THREAD

**Issue by Abraham10000** [Nomena12/SAYNA-HTMLCSS-PANTHER#1]
Bien organiser vos codes en y mettant des : indentation, commentaire et ne mettez pas vos CSS dans un seul fichier mettez les plutôt dans des fichiers distincts pour chaque page. 
Et avant de faire les pop de validation, essayer de bien vérifier les données rentrer les formulaire d'abord.

**Comment by Nomena12** [comment]
Merci pour les corrections.
